### ISSUE TITLE
Add converter for JFR files

### ISSUE THREAD

**Issue by parttimenerd** [mhansen/profilerpedia#23]
https://github.com/parttimenerd/jfrtofp converts JFR (Java) files into FirefoxProfiler and Speedscope files.

**Comment by mhansen** [comment]
Very cool, thanks for letting me know, I'll add them now. Glad to see Firefox Profiler getting more adoption (I think it's great)

**Comment by mhansen** [comment]
Added to spreadsheet: https://docs.google.com/spreadsheets/d/1cVcHofphkQqk1yGeuBPVTit8HQ0oa5SlRM6gkHIagtw/edit#gid=821866908

Deploying now...

**Comment by mhansen** [comment]
Added:

- https://profilerpedia.markhansen.co.nz/converters/jfrtofp/
- https://profilerpedia.markhansen.co.nz/converters/jfrtofp-speedscope/

**Comment by parttimenerd** [comment]
I made a mistake, my converter converts from JFR to the processed format for Firefox Profiler.

**Comment by mhansen** [comment]
I think that's what I've shown in the profilerpedia links above? Could you review and let me know if they're wrong.

**Comment by mhansen** [comment]
Or are you saying that gecko profile is a different format from processed firefox profile?

**Comment by parttimenerd** [comment]
Yes, it is different and you also list [Firefox Processed Profile](https://profilerpedia.markhansen.co.nz/formats/firefox-processed-profile/) as a different format. The Gecko-Format is preprocessed by the Profiler UI.

**Comment by mhansen** [comment]
Ah, thanks. I'll update and redeploy

**Comment by mhansen** [comment]
Should be fixed now
