### ISSUE TITLE
Add Instruments to Gecko Converter

### ISSUE THREAD

**Issue by benjaminRomano** [mhansen/profilerpedia#26]
Hi @mhansen, thanks for maintaining profilerpedia, it's been a very useful resource for me.

I've created a tool, [instruments to gecko](https://github.com/benjaminRomano/instruments-to-gecko), that can convert Instruments Time Profiler data to the Gecko Profile format. This conversion is supported when using XCode 14.3 Beta or higher.

It would be great if this can be included in the list of converters.

**Comment by mhansen** [comment]
Added, thanks!
https://docs.google.com/spreadsheets/d/1cVcHofphkQqk1yGeuBPVTit8HQ0oa5SlRM6gkHIagtw/edit#gid=821866908&range=A133

**Comment by mhansen** [comment]
BTW I'm very glad to see people adapting Firefox Profiler for more use cases. Particularly, mac/iOS could seriously benefit from this converter, their other profiler UI options aren't great! Thank you!
