### ISSUE TITLE
Trace Compass updates

### ISSUE THREAD

**Issue by MatthewKhouzam** [mhansen/profilerpedia#29]
Hi, trace compass maintainer here.

We support: 

* PCAP
* Trace event format
* OTF2

Any way to add them to the graph?

**Comment by mhansen** [comment]
Thank you.

I've added Trace Event Format, I can see that here:
https://eclipse.dev/tracecompass/#:~:text=Multiple%20trace%20formats%20supported

In the link above, it says for OTF2, it has to be converted to CTF. Do you
also support directly reading OTF2 now?

I think I might leave pcap out of scope; I think network tracing is its own
world, that maybe is different enough from software performance profiling
that I don't really want to open that can of worms, I don't have the
expertise in networking, WDYT?

**Comment by MatthewKhouzam** [comment]
OTF2 needs to be converted to CTF. So that's true.

For network tracing, I agree. We use PCAP as a way to annotate kernel traces. But it's a WIDE scope. I understand that you may want to keep that quiet.

Thanks, I will share profilerpedia in my circles.

**Comment by mhansen** [comment]
That's neat, I hadn't heard of using pcap for kernel traces. I suppose it
makes sense, it's all traces. I'll run an update of the site now with the
addition of trace event format
